wn,sne,wn,sn,sn,sn,sn,n,ne,wn,n,sne,wn,n,ne,swn,sn,sn,n,sn,sn,ne,wn,sn,n,sn,ne,swn,sn,n,n,sn,ne,wn,n,sne,wn,sn,sn,sn,ne,wn,sn,sn,sn,sn,sn,sn,n,ne
sw,sn,se,wn,ne,wn,ne,we,w,se,swe,wn,se,we,sw,sn,sn,ne,we,swn,ne,we,sw,ne,sw,ne,sw,sn,ne,swe,w,ne,swe,we,we,wn,se,wn,sn,sne,sw,se,swn,n,ne,wn,sn,sn,se,we
wn,sn,sn,se,we,we,sw,se,we,wn,ne,sw,ne,sw,ne,swn,ne,we,sw,ne,we,sw,sn,se,wne,sw,ne,swn,s,ne,swe,we,wn,se,sw,se,wn,s,sn,sn,sn,n,ne,swe,we,we,wn,n,sne,we
we,wn,sn,ne,w,se,swn,sn,se,we,sw,sn,se,wne,we,wn,se,we,wne,we,w,ne,swn,sn,,ne,sw,sn,ne,sw,ne,sw,s,sn,sn,ne,sw,sne,wn,sn,sn,se,w,sn,se,we,swe,sw,ne,we
we,we,wn,se,swe,wn,sn,sn,sn,se,swn,sn,n,e,we,w,sn,se,we,we,we,sw,sn,sn,se,sw,ne,wn,se,swn,s,sn,ne,swn,sn,s,sn,ne,we,wne,wn,sn,se,wn,ne,sw,sn,ne,w,se
we,we,we,wn,sn,se,wn,n,sn,sn,sn,n,se,swe,we,sw,sn,ne,w,se,we,wn,sn,ne,wn,sne,we,sw,sn,sn,ne,wn,se,wn,sn,sn,ne,we,we,w,se,swn,ne,we,sw,sn,sn,se,sw,ne
we,we,we,sw,ne,wne,we,sw,ne,wn,sne,we,wn,sn,se,wne,wn,se,sw,sn,se,we,wn,se,sw,sn,s,sn,sn,ne,we,sw,ne,we,wn,sne,we,sw,se,sw,sn,sn,e,we,wn,ne,wn,sn,sne,we
w,se,w,sne,we,sw,se,wn,se,we,wn,se,we,swn,sn,e,we,wn,sn,sn,sn,se,we,wn,sn,sn,sn,sn,ne,swe,we,wne,sw,se,sw,ne,we,wn,sn,sn,ne,wne,we,sw,se,we,w,sn,sn,se
we,wne,sw,sn,se,wn,ne,we,swn,,se,wne,sw,sn,ne,we,sw,se,wn,sne,wn,ne,sw,se,wn,ne,wn,ne,sw,sn,se,w,sn,sn,n,e,sw,se,wne,wn,se,sw,se,wn,ne,we,we,swn,n,ne
we,sw,sn,sn,sn,e,we,w,ne,sw,ne,sw,n,ne,we,w,sn,sne,w,sn,se,sw,n,sn,e,sw,se,sw,sn,ne,swn,se,wn,sn,se,sw,ne,wn,s,se,wn,sn,sn,e,sw,se,sw,sn,se,we
sw,sn,ne,wn,sn,se,we,swe,we,wn,s,sn,se,we,we,w,ne,wn,se,wne,wn,ne,sw,ne,swe,wn,ne,wn,ne,sw,sn,sn,se,wne,wn,sn,se,we,wn,sn,se,wn,ne,swe,wn,ne,wn,sn,sn,se
wn,ne,we,sw,ne,wn,se,wn,se,swe,wn,sn,ne,swe,we,we,sw,se,wn,e,we,w,ne,sw,ne,we,sw,se,sw,sn,sn,ne,swn,s,s,sne,wn,se,we,wn,sn,se,sw,sn,se,we,sw,sn,ne,wne
we,swe,sw,sn,se,we,wn,e,wn,ne,we,swn,s,sn,se,we,wn,sn,se,sw,se,we,sw,ne,we,sw,sn,ne,wne,wn,ne,sw,ne,wn,sn,ne,we,swn,s,s,sn,sn,sne,wn,sn,se,wn,sne,sw,e
sw,ne,wn,ne,wn,se,swe,w,se,we,sw,ne,swn,sn,n,se,swe,wn,sn,ne,wn,e,swn,se,sw,sn,sn,se,sw,se,we,wn,se,sw,ne,we,sw,sn,sn,sn,sn,sn,ne,we,swn,ne,w,n,sne,we
wn,se,we,sw,se,wn,ne,sw,ne,sw,ne,we,wn,ne,sw,ne,wn,se,swn,s,se,swe,wn,n,ne,wn,sn,n,sn,ne,we,we,wn,ne,we,sw,sn,sn,sn,ne,wn,sn,se,sw,ne,we,we,sw,ne,we
we,wn,se,wn,sn,se,we,swn,se,wn,e,sw,se,we,wne,we,sw,sn,sn,sn,sn,ne,we,we,swe,w,sne,we,wne,we,we,sw,se,we,sw,sn,ne,wn,ne,sw,se,swn,n,sn,se,w,s,sne,we,we
we,we,wn,s,ne,wne,we,wn,sn,se,we,wn,sn,se,we,sw,sn,sn,ne,wn,n,se,we,sw,ne,we,wn,se,we,we,sw,ne,wn,se,wn,ne,we,we,sw,ne,swn,n,se,swn,sn,se,wn,ne,we,we
we,we,swe,wn,se,sw,s,se,swn,sn,se,sw,ne,wn,se,wn,sn,ne,we,we,we,wn,se,wne,sw,se,sw,ne,we,we,wn,e,sw,ne,we,sw,se,we,wne,sw,ne,w,sn,ne,wn,sn,se,we,we,we
we,sw,ne,we,wn,sn,sn,ne,wn,sn,sn,sn,se,we,wn,se,wne,sw,se,we,swe,we,swn,,sn,sn,sne,we,w,se,we,we,wn,se,we,wne,wn,e,sw,ne,we,sw,ne,sw,se,wn,sne,we,sw,se
sw,ne,we,we,sw,ne,swn,s,se,wn,sn,sn,ne,we,we,swn,,ne,wn,s,sn,se,wn,se,wn,sn,ne,we,sw,sn,e,swe,sw,sn,se,sw,se,we,wn,se,sw,ne,sw,ne,swn,,ne,sw,sn,ne
wn,e,sw,e,wne,sw,sn,ne,wn,se,wn,sn,se,we,sw,ne,we,swe,we,swn,sn,n,se,wn,se,wn,se,w,ne,swn,se,wn,sn,n,sn,sn,sn,se,sw,n,sn,se,swn,s,ne,swe,sw,n,sne,we
we,sw,sne,we,w,n,sne,we,w,ne,sw,sn,ne,we,wn,se,we,wn,se,wn,ne,sw,ne,we,wne,sw,ne,we,sw,sn,sn,se,wne,sw,sn,sn,ne,wn,ne,sw,ne,wn,sn,ne,sw,sn,sn,se,wn,e
w,sn,ne,sw,se,we,wn,se,swe,sw,ne,swn,s,se,we,wn,e,w,sn,se,sw,sn,se,we,w,sn,se,sw,sn,sn,sn,ne,w,ne,swn,ne,sw,se,we,swn,s,se,wne,sw,sn,sn,sn,sn,se,we
sw,sne,sw,n,sn,se,we,wn,sn,sn,e,wn,sn,sn,se,swe,sw,se,wn,sn,sn,ne,wn,se,we,wn,sn,n,sne,wn,sn,se,we,sw,ne,w,ne,wne,sw,sn,sn,ne,sw,sn,sn,sn,sn,ne,wn,se
wn,sn,ne,sw,sn,sne,we,we,wn,ne,swe,sw,sn,ne,swn,n,sn,sn,se,wn,sne,sw,se,wn,se,we,wne,we,wn,se,swn,n,se,wne,we,we,we,we,wn,sn,ne,we,wn,sn,sn,sn,sn,e,sw,ne
w,ne,sw,sn,sn,sn,se,sw,se,sw,sn,ne,wn,se,wn,se,wn,sn,ne,sw,sn,sn,sn,e,wne,we,we,we,we,swn,n,se,wn,e,we,we,sw,se,sw,ne,sw,se,sw,ne,swn,n,sne,w,sne,we
we,we,wn,sn,ne,wn,sn,sn,ne,wn,sn,se,sw,ne,we,wn,se,wne,sw,sn,sn,sn,ne,we,sw,s,e,we,sw,ne,we,wn,se,sw,s,se,wn,n,sn,se,swn,n,ne,sw,ne,we,wn,se,wn,se
we,we,sw,ne,sw,s,sn,sne,we,we,wn,ne,wn,se,we,we,swn,,ne,swn,n,sne,we,sw,ne,swn,se,sw,ne,we,we,we,wne,wn,ne,wn,se,swe,wn,ne,wn,se,we,wn,se,sw,e,wne,sw,ne
we,sw,ne,sw,n,sne,wn,sn,se,we,we,sw,se,wn,e,sw,sn,se,we,wn,se,wn,se,wne,we,wn,sn,ne,sw,s,se,we,w,se,we,sw,sn,sn,se,we,w,ne,we,sw,sn,ne,sw,e,wn,se
we,wne,sw,sn,se,wn,se,wne,wn,s,se,swn,sn,e,sw,sn,sn,ne,sw,e,wn,se,wn,se,we,we,wne,sw,sn,ne,swn,e,swe,wn,e,swn,ne,wn,sn,se,we,we,sw,sn,ne,we,wne,we,we,wne
sw,s,sne,wn,sn,se,wn,e,sw,ne,wn,sn,ne,we,swn,ne,wn,se,wn,se,we,wn,s,sn,e,we,w,sn,ne,sw,ne,sw,sn,se,sw,sn,se,sw,ne,wne,we,sw,ne,wn,se,we,sw,se,we,we
wn,n,sn,se,swn,n,e,sw,sne,sw,se,wn,se,sw,n,se,we,wn,se,wn,se,swe,wn,ne,sw,se,we,wne,sw,ne,sw,sn,sn,sn,sn,ne,wn,sn,se,w,se,wn,se,w,sn,se,wn,ne,we,we
we,we,wn,sn,ne,swe,sw,sn,n,sn,ne,we,swn,sn,e,wn,se,sw,ne,sw,sn,ne,we,sw,ne,wn,e,sw,n,se,wn,n,ne,wn,sn,se,sw,sn,ne,we,wne,sw,ne,swe,wn,sn,se,we,sw,e
we,swe,w,sne,sw,sn,n,ne,we,wne,we,sw,sn,ne,we,we,wn,sn,s,sn,ne,sw,se,wne,we,swe,sw,ne,w,sne,we,we,we,sw,sn,sn,ne,wn,se,sw,s,ne,sw,ne,w,sne,wn,e,wn,se
we,wn,se,wn,sn,ne,we,we,we,we,we,wn,ne,we,we,sw,s,sne,wn,ne,sw,sn,sn,e,sw,ne,wn,se,we,wn,se,we,swe,wn,ne,wn,se,sw,sn,ne,wn,se,wne,sw,se,wn,se,swe,we,wne
we,sw,ne,we,wn,se,we,we,sw,e,sw,se,sw,se,swe,wn,sn,sn,se,we,wn,ne,swn,se,wn,se,we,swn,e,sw,ne,sw,sn,se,sw,se,wn,n,sn,se,sw,sn,e,wn,sn,e,wn,ne,we,we
sw,sn,se,we,we,swn,se,we,wn,se,wne,wn,ne,wn,n,se,wn,sn,sne,we,we,sw,sn,ne,sw,ne,sw,ne,sw,ne,we,wn,ne,swn,n,ne,swe,we,swn,n,n,sne,we,sw,ne,swe,we,we,we,we
wn,sn,ne,we,we,wn,sn,se,sw,ne,we,we,sw,se,we,swn,,sn,sn,se,we,wn,ne,sw,sn,se,wn,se,wn,se,sw,se,sw,ne,we,sw,ne,sw,ne,we,sw,sn,s,sne,we,wn,se,sw,se,we
sw,ne,we,we,sw,se,wne,wn,ne,we,sw,se,wn,ne,sw,ne,sw,sn,ne,swn,e,we,w,sn,sn,sne,w,ne,swe,wn,sn,sn,ne,we,sw,ne,sw,sn,se,we,wne,wn,sn,sn,se,we,swn,sn,n,e
swn,se,sw,se,swn,sn,s,se,sw,s,sn,sn,se,sw,sn,se,swn,sn,s,sn,se,swe,sw,sn,sn,sn,se,sw,sn,s,sn,sne,sw,s,sn,se,swn,sn,sn,s,se,sw,sn,sn,sn,s,sn,sn,se,swe