swn,n,sn,ne,swn,n,sn,sne,wn,ne
wn,se,swn,e,wn,se,wn,ne,we,we
we,wn,ne,we,w,sn,se,sw,se,we
sw,se,we,we,we,wn,sn,sn,ne,we
wn,sn,se,we,swe,we,swn,sn,s,e
we,swn,ne,sw,ne,sw,sn,sn,ne,we
sw,ne,w,sne,sw,sn,sn,sn,se,we
wn,se,we,wn,ne,wn,ne,wn,sn,se
we,swn,e,we,sw,se,we,sw,sn,ne
sw,ne,sw,se,wn,sn,se,wn,sn,se
wn,se,wn,ne,sw,sn,sn,e,swn,ne
w,ne,we,sw,sn,sn,ne,sw,sn,e
we,sw,se,swn,sn,ne,sw,ne,wne,we
sw,ne,wn,n,sn,s,ne,we,sw,se
wn,se,we,we,wn,ne,swe,we,wn,ne
we,swn,e,swe,we,sw,ne,sw,se,we
sw,ne,we,wn,se,wn,se,wn,sn,e
swn,s,e,sw,ne,we,wn,se,wn,se
wn,ne,sw,sne,we,we,we,wne,we,wne
swe,sw,sn,sn,se,sw,se,sw,s,se