swn,n,ne,wn,sn,sn,sn,sn,sn,sn,sn,n,sn,ne,wn,sn,n,sn,sne,wn,n,sn,sn,n,sn,sne,wn,n,sn,ne
wn,se,swe,sw,sn,ne,wn,sn,sn,sn,ne,sw,ne,swe,we,wn,se,wn,sn,se,we,wn,ne,swe,wn,sn,se,sw,ne,we
w,sn,sn,ne,wn,se,w,ne,wn,ne,swe,wn,se,wn,se,we,wn,se,swn,ne,sw,se,sw,ne,we,wn,sn,ne,we,swe
swe,wn,sn,se,sw,ne,swe,sw,se,sw,ne,sw,sn,se,wne,we,sw,ne,wn,s,sne,wn,ne,sw,se,w,ne,swe,sw,ne
wn,se,wn,n,sne,sw,sn,sn,ne,wn,s,ne,wn,n,se,sw,ne,we,w,ne,wn,se,sw,n,ne,we,sw,n,ne,we
w,sn,se,sw,sn,n,sn,sne,sw,se,wne,we,we,we,wn,sn,e,we,swe,sw,,sne,wn,se,we,sw,sne,we,swe,we
we,swn,sn,sn,ne,sw,sn,n,sn,sn,se,sw,se,we,we,swn,se,we,wn,ne,swe,wn,se,wne,sw,sn,ne,sw,ne,we
we,wn,sn,sn,s,ne,wne,sw,sn,sn,sn,sn,sn,se,sw,sn,ne,sw,se,sw,ne,we,swn,,sne,wn,s,sn,se,we
we,we,wn,sn,ne,we,w,n,sn,ne,wn,sn,sn,sne,wn,sn,e,wne,wn,sn,se,sw,ne,w,sn,se,wn,sn,sn,se
sw,se,w,ne,we,we,swe,w,ne,w,se,wn,sn,ne,we,swn,s,se,we,swn,sn,n,se,sw,sn,sne,w,sn,sn,ne
swn,sn,se,we,we,sw,ne,swe,we,we,wn,s,sne,we,sw,sn,sn,sn,s,sn,sn,se,wn,sn,sn,ne,sw,sn,ne,we
wn,sn,sn,se,swe,wn,se,wn,se,swe,we,wn,ne,sw,sn,n,ne,wne,wn,ne,wn,sn,se,wn,sne,sw,sn,ne,swe,we
sw,sn,sn,ne,wn,se,swn,s,sn,sn,se,we,sw,ne,wn,se,w,se,we,sw,se,swn,ne,w,ne,wn,ne,sw,sn,e
wn,sn,sn,e,sw,sn,ne,wn,sn,sn,n,se,swn,s,se,swn,se,wn,se,wn,sn,n,se,we,sw,se,sw,sn,ne,we
we,wn,sn,s,sne,wn,se,we,wn,sne,we,wn,sn,sn,ne,wn,sn,se,wne,sw,ne,we,wn,se,wn,sn,ne,wn,se,we
we,sw,sn,sne,wn,s,sn,se,sw,sn,se,we,wn,sn,se,sw,sn,ne,sw,ne,we,sw,se,wn,se,wne,we,sw,ne,we
sw,sn,sn,n,s,sne,wn,sn,ne,wn,sn,se,we,wn,sn,n,sn,se,wn,e,we,wn,sn,se,wn,e,we,wne,sw,se
wn,sn,ne,sw,ne,wn,se,wne,we,we,wn,sne,we,swe,wn,se,wn,sn,e,swe,sw,se,swn,ne,we,we,we,sw,sn,ne
sw,ne,we,swn,se,sw,ne,we,sw,se,we,wn,se,wn,se,wne,we,wne,sw,sn,n,sn,sn,se,we,sw,se,wn,ne,we
swn,se,sw,sn,sn,sn,se,sw,sn,sn,s,s,sn,se,swn,s,s,s,sn,sne,sw,sn,sn,sn,s,sn,sn,se,sw,se